version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "9050:9050"
    volumes:
      - app_data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production

volumes:
  app_data:
    driver: local